### ISSUE TITLE
Only default source works

### ISSUE THREAD

**Issue by drowrin** [VTTAssets/discord-ambience-bot#2]
Hi! First I want to say thank you for this, it fits my needs perfectly.

Wanted to report a minor issue though: the bot only works when I leave the id null. otherwise I get the error `Cannot join VoiceChannel, because Channel count exceeds maximum number of channels for device` and then the bot crashes.

Something I noticed that may be related: it appears that the default selected is always an Input device, but listAudioHardware.js lists output devices.

**Comment by philmeth** [comment]
Hey :)
I have the same problem. It all connects fine, but beside the default device all give said error.

Heres the ps log if it helps:

> PortAudio V19.6.0-devel, revision unknown
Input audio options: device 2, sample rate 44100, channels 2, bits per sample 16, max queue 2
Input device name is Microsoft Sound Mapper - Output
PID 4724 received SIGSEGV for address: 0x3646d759
SymInit: Symbol-SearchPath: '.;C:\Users\p***s\Desktop\discord-ambience-bot-master;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'p***s'
OS-Version: 10.0.19042 () 0x300-0x1
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FF8387283DC (ntdll): (filename not available): RtlDeleteAce
00007FF8386FB406 (ntdll): (filename not available): RtlRaiseException
00007FF8386FB335 (ntdll): (filename not available): RtlRaiseException
00007FF83646D759 (KERNELBASE): (filename not available): RaiseException
d:\agent\_work\2\s\src\vctools\crt\vcruntime\src\eh\throw.cpp (133): _CxxThrowException
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\naudiodon\src\pacontext.cc (228): streampunk::PaContext::setParams
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\naudiodon\src\pacontext.cc (66): streampunk::PaContext::PaContext
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\naudiodon\src\audioio.cc (127): streampunk::AudioIO::AudioIO
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\node-addon-api\napi-inl.h (61): Napi::details::WrapCallback<<lambda_eeccb9d2c1adfc3a81d74277a63b25af> >
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\node-addon-api\napi-inl.h (3286): Napi::ObjectWrap<streampunk::AudioIO>::ConstructorCallbackWrapper
00007FF6D28C6076 (node): (filename not available): node::Stop
00007FF6D313724F (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D313646C (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D3136AC0 (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D3136913 (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D32125AD (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31A7DD1 (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D329D471 (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31AAE32 (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31A7CDA (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D329D471 (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31AAE32 (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D325EB5E (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31CA0CF (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31A89DC (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D30723EC (node): (filename not available): v8::internal::Execution::CallWasm
00007FF6D30724FB (node): (filename not available): v8::internal::Execution::CallWasm
00007FF6D3072F7A (node): (filename not available): v8::internal::Execution::TryCall
00007FF6D304DD25 (node): (filename not available): v8::internal::MicrotaskQueue::RunMicrotasks
00007FF6D304DA80 (node): (filename not available): v8::internal::MicrotaskQueue::PerformCheckpoint
00007FF6D313724F (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D31367D4 (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D3136AD5 (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D3136913 (node): (filename not available): v8::internal::Builtins::builtin_handle
00007FF6D32125AD (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31AAE32 (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31A8AEE (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D31A86DC (node): (filename not available): v8::internal::SetupIsolateDelegate::SetupHeap
00007FF6D307232D (node): (filename not available): v8::internal::Execution::CallWasm
00007FF6D3071B9F (node): (filename not available): v8::internal::Execution::Call
00007FF6D3164EB7 (node): (filename not available): v8::Function::Call
00007FF6D291AEB1 (node): (filename not available): node::CallbackScope::~CallbackScope
00007FF6D291B1FB (node): (filename not available): node::CallbackScope::~CallbackScope
00007FF6D29121E4 (node): (filename not available): v8::internal::compiler::Operator::EffectOutputCount
00007FF6D27B0F33 (node): (filename not available): v8::internal::wasm::WasmCode::code_comments_offset
00007FF6D27B1AAD (node): (filename not available): v8::internal::wasm::WasmCode::code_comments_offset
00007FF6D2726BA9 (node): (filename not available): std::basic_streambuf<char,std::char_traits<char> >::xsputn
00007FF6D2726E40 (node): (filename not available): std::basic_streambuf<char,std::char_traits<char> >::xsputn
00007FF6D272B737 (node): (filename not available): std::basic_streambuf<char,std::char_traits<char> >::xsputn
00007FF6D27AC7C9 (node): (filename not available): v8::internal::wasm::WasmCode::code_comments_offset
00007FF6D293507B (node): (filename not available): uv_tty_set_vterm_state
00007FF6D294ABDC (node): (filename not available): uv_loop_init
00007FF6D294AEEA (node): (filename not available): uv_run
00007FF6D291A5B4 (node): (filename not available): node::SpinEventLoop
00007FF6D2848A77 (node): (filename not available): v8::internal::AsmJsScanner::GetIdentifierString
00007FF6D28BCD4B (node): (filename not available): node::Start
00007FF6D26F7CFC (node): (filename not available): RC4_options
00007FF6D372340C (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FF837867034 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FF8386FD0D1 (ntdll): (filename not available): RtlUserThreadStart
Error: Channel count exceeds maximum number of channels for device
    at new AudioIO (C:\Users\p***s\Desktop\discord-ambience-bot-master\node_modules\naudiodon\index.js:32:23)
    at C:\Users\p***s\Desktop\discord-ambience-bot-master\index.js:76:16
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
PID 4724 received SIGSEGV for address: 0xcc89614
SymInit: Symbol-SearchPath: '.;C:\Users\p***s\Desktop\discord-ambience-bot-master;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'p***s'
OS-Version: 10.0.19042 () 0x300-0x1
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FF8387283DC (ntdll): (filename not available): RtlDeleteAce
00007FF8386FB406 (ntdll): (filename not available): RtlRaiseException
00007FF83874FE3E (ntdll): (filename not available): KiUserExceptionDispatcher
c:\users\p***s\desktop\discord-ambience-bot-master\node_modules\node-addon-api\napi-inl.h (3407): Napi::ObjectWrap<streampunk::AudioIO>::FinalizeCallback
00007FF6D28B54E6 (node): (filename not available): node_module_register
00007FF6D28F0F85 (node): (filename not available): napi_wrap
00007FF6D28DB7E9 (node): (filename not available): napi_wrap
00007FF6D2940498 (node): (filename not available): uv_check_init
00007FF6D294B0B8 (node): (filename not available): uv_run
00007FF6D291A5B4 (node): (filename not available): node::SpinEventLoop
00007FF6D2848A77 (node): (filename not available): v8::internal::AsmJsScanner::GetIdentifierString
00007FF6D28BCD4B (node): (filename not available): node::Start
00007FF6D26F7CFC (node): (filename not available): RC4_options
00007FF6D372340C (node): (filename not available): v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
00007FF837867034 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FF8386FD0D1 (ntdll): (filename not available): RtlUserThreadStart

**Comment by philmeth** [comment]
Also when I am getting sound, It very guickly crashes and disconnects from the channel.
Heres the log for that:

> PortAudio V19.6.0-devel, revision unknown
Input audio options: default device, sample rate 44100, channels 2, bits per sample 16, max queue 2
Input device name is CABLE Output (VB-Audio Virtual
AudioIO: portAudio status - input overflow
AudioIO end
AudioIO close

**Comment by NutritiousCookie** [comment]
listAudioHardware.js is broken. If you remove `.filter(device => device.maxOutputChannels !== 0)` it will give you the full list of devices. If you know which device you want, you can find the id that way.

**Comment by VTTAssets** [comment]
I had a look at that code and many of the underlying libraries changed significantly since I wrote this:

discord.js on v13 has a vastly different way of handling voice channels and the audio-probe wrapper does not work like it used at all in recent versions. I will not recommend using this as-is even if it works a little bit due to outdated and vulnerable libraries.

See this example on the current discord.js voice implementation: https://github.com/discordjs/voice/tree/main/examples/radio-bot

It relies on an installed ffmpeg, but works otherwise okayish, with a smallish lag (~2 seconds on my tests). It's suited way better for your needs as of now (still needs some loopback device via VB Audio Cable or other hardware interfaces providing such a functionality. That wasn't necessary in the code found in this repo, but alas, it doesn't work that way any longer)
